# Generated by Django 5.2.7 on 2025-10-07 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alert", "0001_initial"),
        ("products", "0008_alter_productmetadata_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="products.product",
            ),
        ),
    ]
