# Generated by Django 5.2.7 on 2025-10-12 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alert", "0002_alter_alert_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertMet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("triggered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "alert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="met_events",
                        to="alert.alert",
                    ),
                ),
            ],
        ),
    ]
