# Generated by Django 5.2.7 on 2025-10-12 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_user_email"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DemoToken",
        ),
    ]
