# Generated by Django 5.2.6 on 2025-10-02 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductMetaData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="products/")),
            ],
        ),
        migrations.RenameModel(
            old_name="Price",
            new_name="PriceHistory",
        ),
        migrations.RemoveField(
            model_name="xpath",
            name="field",
        ),
        migrations.RemoveField(
            model_name="product",
            name="name",
        ),
        migrations.RemoveField(
            model_name="xpath",
            name="selector",
        ),
        migrations.AddField(
            model_name="xpath",
            name="image_selector",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="xpath",
            name="price_selector",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="xpath",
            name="title_selector",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="meta",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.productmetadata",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Field",
        ),
    ]
