# Generated by Django 5.2.6 on 2025-10-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_productmetadata_rename_price_pricehistory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="xpath",
            name="image_cleanup",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="xpath",
            name="price_cleanup",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="xpath",
            name="title_cleanup",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
