# Generated by Django 5.2.6 on 2025-10-04 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_xpath_image_cleanup_xpath_price_cleanup_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="website",
            old_name="domain",
            new_name="url",
        ),
    ]
