# Generated by Django 5.2.6 on 2025-10-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_rename_domain_website_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="website",
            name="scraping_method",
            field=models.CharField(default="playwright", max_length=255),
            preserve_default=False,
        ),
    ]
