# Generated by Django 5.2.6 on 2025-10-04 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_website_scraping_method"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="website",
        ),
        migrations.AddField(
            model_name="product",
            name="website",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="products.website",
            ),
            preserve_default=False,
        ),
    ]
