# Generated by Django 5.2.7 on 2025-10-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_remove_product_website_product_website"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricehistory",
            name="checked_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
