# Generated by Django 5.2.7 on 2025-10-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_alter_pricehistory_checked_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmetadata",
            name="image",
            field=models.CharField(),
        ),
    ]
