# Generated by Django 5.2.7 on 2025-10-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_currency_website_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="currency",
            name="currency_name",
            field=models.CharField(default="", max_length=10),
            preserve_default=False,
        ),
    ]
