# Generated by Django 5.2.7 on 2025-10-12 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_currency_currency_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricehistory",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prices",
                to="products.product",
            ),
        ),
    ]
